SELECT DISTINCT PATIENT_ID,ADDED_DATE,MODIFIED_DATE
FROM [SiIMC_MGHT].[dbo].[T_BL_ENCOUNTER_PAYER_PRIORITY]
WHERE CAST(ADDED_DATE AS DATE) >= CAST(GETDATE() - 3 AS DATE) 
 or
	     cast(MODIFIED_DATE as date) >= cast(getdate()-3 as date)
AND NOT EXISTS (
    SELECT 1 
    FROM [SiIMC_MGHT].[dbo].[T_BL_ENCOUNTER_PAYER_PRIORITY] AS ep
    WHERE CAST(ep.ADDED_DATE AS DATE) = CAST(GETDATE() - 4 AS DATE)
          AND ep.PATIENT_ID = [SiIMC_MGHT].[dbo].[T_BL_ENCOUNTER_PAYER_PRIORITY].PATIENT_ID
)
ORDER BY ADDED_DATE DESC